[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }
config = { "clangd.fallbackFlags" = [ "-std=c++20" ] }
diagnostic-severity = "Error"
language-server = { command = "clangd" }

[[language]]
name = "python"
indent = { tab-width = 4, unit = "    " }
diagnostic-severity = "Error"
language-server = { command = "pylsp" }

[[language]]
name = "html"
scope = "text.html.basic"
injection-regex = "html"
file-types = ["html"]
roots = []
language-server = { command = "vscode-html-language-server", args = ["--stdio"] }
auto-format = true
config = { "provideFormatter" = true }
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "go"
indent = { tab-width = 4, unit = "    " }
diagnostic-severity = "Error"
language-server = { command = "gopls" }
config = { "unusedparams" = false }